### PR TITLE
More visible block cursor

### LINKED ISSUE #2: Text under block caret is hard to read
First off all, thank you for the great color scheme!

I'm using VS Code with the Vim package which changes the style of the caret into a block (in normal mode; in insert mode it's the same as the default). I propose changing the caret color to a more neutral color (#c0c5ce works pretty nicely) to improve the contrast between the underlying text and the block caret.

A screenshot of the problem, with the fix applied on the right:
carets

### PR DESCRIPTION
**Pull request by zsparal**
Feel free to close the PR if you don't think it's a big enough issue. Closes #2

### CODE REVIEW

**Comment by azemoh** [comment]
Hey @Gustorn thanks for the PR. I would love to keep the blue cursor in line with the original theme. But we could make the text color white, to improve readability.

**Comment by zsparal** [comment]
Unforunately there's no way to set the caret background and foreground colors separately, which is why I sent the PR as is. See [here](https://github.com/Microsoft/vscode/blob/0a50b220632517456de3d9381157c8441a298099/src/vs/workbench/services/themes/electron-browser/stylesContributions.ts#L359) in the VS Code codebase for details.

**Comment by azemoh** [comment]
Oh that's a shame. Thanks, @Gustorn. I'll close this cos I want to maintain the original color scheme. What you can do is edit your User Settings and set `editor.cursorStyle` to `line`.

**Comment by zsparal** [comment]
I know I can edit the cursor style, but that completely kills the Vim emulation. I don't mind editing the color every time there's an update, but know that this severely limits accessibility for everyone using the block version (which is not necessarily a bad thing, but it's worth noting)

**Pull request closed without merging**
